services:
  webapp:
    build:
      context: .
    ports:
      - "5500:5500"
    volumes:
      - ./app/uploads:/app/uploads
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - FLASK_APP=app
      - FLASK_ENV=development
