services:
  webapp:
    build:
      context: .
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ./app/uploads:/app/uploads
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - FLASK_APP=app
      - FLASK_ENV=development
      - PORT=${PORT}
